server:
  port: 1200
spring :
   application :
      name : authService 
   redis:
    database: 0
    host: 139.199.21.16
    port: 6379
    password: redis
    timeout: 60s
   zipkin:
     base-url: http://localhost:7777
     locator:
        discovery:
            enabled: true
   sleuth:
    sampler:
      probability: 1.0
    web:  
           skipPattern : (^cleanup.*)     
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
jwt:
  blacklist:
    key:
      format: JWT_BLACKLIST::%s
  refresh:
    token:
      key:
        format: JWT_REFRESH_TOKEN::%s
  secret:
    key: asdfghjkl
refresh:
  token:
    expire:
      time: 120000
token:
   expire:
    time: 60000  
    
      
feign:  #启用hystrix监控
  hystrix:
    enabled: true     