server:
  port: 10888
spring :
   application :
      name : authService 
   redis:
    database: 0
    host: 139.199.21.16
    port: 6379
    password: redis
    timeout: 60s
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 1234  
   security:
     basic:
      enabled: false    
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka/
      
authorizationparam:
  client-id: 123456 
  secret: 123456 
  scopes: read,write 
  authorized-grant-types: implicit, refresh_token, password, authorization_code
  token-expire: 10000 
  token-refresh: 1500 
  
  
#  授权码模式（authorization_code）（即先登录获取code,再获取token)

#  简化模式（implicit）简化模式(在redirect_uri 的Hash传递token; Auth客户端运行在浏览器中,如JS,Flash)

#  密码模式（password）密码模式(将用户名,密码传过去,直接获取token)

#  客户端模式（client credentials）客户端模式(无用户,用户向客户端注册,然后客户端以自己的名义向’服务端’获取资源)




